### ISSUE TITLE
v=19 parameter

### ISSUE THREAD

**Issue by philtay** [P-H-C/phc-string-format#1]
Argon 1.3 introduced a new parameter (i.e. `v=19`) to its string format. The [reference C implementation](https://github.com/p-h-c/phc-winner-argon2) now produces hashes like this `$argon2i$v=19$m=512,t=2,p=2$5VtWOO3cGWYQHEMaYGbsfQ$AcmqasQgW/wI6wAHAMk4aQ`. According to the format documented in this repository the `v=19` parameter is illegal. Ref: https://github.com/hynek/argon2_cffi/issues/12

**Comment by simonepri** [comment]
@pornin @veorq  Any news about that?

**Comment by dimaqq** [comment]
✳
